#include <stdio.h>
#include <stdlib.h>

#include "gba_video.h"
#include "gba_systemcalls.h"
#include "gba_input.h"
#include "gba_interrupt.h"
#include "mappy.h"
#include "pcx.h"
#include "fade.h"

#include "splash_scr.h"
#include "graphics_controller.h"
#include "input_controller.h"

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "title_pcx.h"
#include "title_pulse_pcx.h"
#include "main_menu_pcx.h"

void splash_HandleInputs();

typedef enum TILE_STATE {
	EMPTY = 0,
	SLUG_HERE,
	SLUG_HIT,
	MISS_HIT
} TILE_STATE;

typedef struct TILE {
	u16 x;
	u16 y;
	TILE_STATE state;
} Tile;

typedef struct SLUG {
	u16 size;
	bool isActive;
	bool isDead;
	Tile *coords;
} SLUG;

//---------------------------------------------------------------------------------
// Function Declarations
//---------------------------------------------------------------------------------

/**
 * Initialises a 2-dimensional matrix of tiles by the given width and height.
 * Returns a pointer to the final array
 * @param width The width of the final matrix.
 * @param height The height of the final matrix.
 */
Tile * InitTileMatrix(u16 width, u16 height);

/**
 * Initialises a slug based on the given Tile matrix of the given size.
 * @param map The tilemap to base the slug on.
 * @param maxWidth The maximum width of the slug, equal to or less than the width of the provided tilemap.
 * @param maxHeight The maximum height of the slug, equal to or less than the height of the provided tilemap.
 */
SLUG * CreateSlug(Tile * map, u16 maxWidth, u16 maxHeight, u16 size);

/**
 * Destroys the given slug, freeing its memory.
 * @param slug The slug to free up.
 */
void DestroySlug(SLUG * slug);

//---------------------------------------------------------------------------------
// Globals
//---------------------------------------------------------------------------------

#define SLUG_SIZE 5
#define HANGAR_WIDTH 5
#define HANGAR_HEIGHT 5


//---------------------------------------------------------------------------------
// Program entry point
//---------------------------------------------------------------------------------
int main(void)
//---------------------------------------------------------------------------------
{

	time_t t;
	srand((unsigned) time(&t));

	Tile * tiles = InitTileMatrix(HANGAR_HEIGHT, HANGAR_WIDTH);

	SLUG * slug = CreateSlug(tiles, HANGAR_WIDTH, HANGAR_HEIGHT, SLUG_SIZE);

	// Set up the interrupt handlers
	//irqInit();
	// Enable Vblank Interrupt to allow VblankIntrWait
	//irqEnable(IRQ_VBLANK);

	//SetMode(MODE_4 | BG2_ON);		// screen mode & background to display

	// Load all necessary image data
	//graphics_LoadImage(title_pcx, &PaletteBuffer);
	//graphics_LoadImage(title_pulse_pcx, &PulsePaletteBuffer);

	//splash_screen_eff = splash_PulseGray;	// Set the initial screen mode
	//splash_set_pal1(&PaletteBuffer);		// Load the first palette
	//splash_set_pal2(&PulsePaletteBuffer);	// Load the second palette

	//dprintf("Initialised application with palettes %p, %p\n", &PaletteBuffer, &PulsePaletteBuffer);

	while (1)
	{
		//VBlankIntrWait();
		//graphics_Update();
		// Process key inputs
		//input_key_reads();
		//splash_HandleInputs();
	}

	free(tiles);
	DestroySlug(slug);

}

Tile * InitTileMatrix(u16 width, u16 height) {
	
	// Begin by allocating enough memory to store an array of the desired amount of tiles
	Tile * tiles = malloc(sizeof tiles * (width * height));

	for (int x = 0; x < width; x++) {
		for (int y = 0; y < height; y++) {
			Tile * tile = &tiles[(x * height) + y];
			tile->x = x;
			tile->y = y;
			tile->state = EMPTY;
			dprintf("Initialised Tile %d %d at location %p\n", tile->x, tile->y, tile);
		}
	}

	return tiles;
}

SLUG * CreateSlug(Tile * map, u16 maxWidth, u16 maxHeight, u16 size) {

	u32 currTile;
	u16 randX;		//< Random x-coordinate buffer
	u16 randY;		//< Random y-coordinate buffer

	SLUG * slug = malloc(sizeof * slug);				//< The slug to create
	Tile ** coords = malloc(sizeof (Tile *) * size);	//< The coordinates of the slug

	slug->coords = *coords;	//< Assign the new coords array to the slug.

	// Temporary initialisation of the coords array by assigning test pointers
	for (int tile = 0; tile < size; tile++) {
		coords[tile] = map + tile;
	}

	// Testing of the assigned coords tiles
	for (int tile = 0; tile < size; tile++) {
		dprintf("Testing referenced Tile %d %d at location %p\n", coords[tile]->x, coords[tile]->y, coords[tile]);
	}

	return slug;

}

void DestroySlug(SLUG * slug) {
	free(slug->coords);
	free(slug);
}

Tile * Back_InitTileMatrix() {

	// Begin by allocating enough memory to store an array of the desired amount of tiles
	Tile tiles[HANGAR_WIDTH][HANGAR_HEIGHT];

	for (int x = 0; x < HANGAR_WIDTH; x++) {
		for (int y = 0; y < HANGAR_HEIGHT; y++) {
			tiles[x][y].x = x;
			tiles[x][y].y = y;
			tiles[x][y].state = EMPTY;
			dprintf("Initialised Tile %d %d at location %p\n", tiles[x][y].x, tiles[x][y].y, &tiles[x][y]);
		}
	}

	return tiles;

}

void splash_HandleInputs() {
	if (input_key_pressed(KEY_UP) && splash_screen_eff != splash_PulseGray)				splash_screen_eff = splash_PulseGray;
	else if (input_key_pressed(KEY_RIGHT) && splash_screen_eff != splash_Pulse_Title)	splash_screen_eff = splash_Pulse_Title;
	else if (input_key_pressed(KEY_DOWN) && splash_screen_eff != splash_FadeOut)		splash_screen_eff = splash_FadeOut;
	else if (input_key_pressed(KEY_LEFT))												graphics_TransNewImage(main_menu_pcx);
}