#include "gba_video.h"
#include "gba_systemcalls.h"
#include "gba_input.h"
#include "gba_interrupt.h"
#include "mappy.h"
#include "pcx.h"
#include "fade.h"

#include "tile.h"
#include "slug.h"
#include "hangar.h"
#include "splash_scr.h"
#include "graphics_controller.h"
#include "input_controller.h"

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "title_pcx.h"
#include "title_pulse_pcx.h"
#include "main_menu_pcx.h"
#include "GROUND_EXP_pcx.h"

void splash_HandleInputs();
void hangar_HandleInputs();

//---------------------------------------------------------------------------------
// Function Declarations
//---------------------------------------------------------------------------------

//---------------------------------------------------------------------------------
// Globals
//---------------------------------------------------------------------------------

#define SLUG_SIZE 5

#define SB_PAGE 31

Tile * tiles;
Slug * slug;

int selectX;		//< Selected slug grid tile on X-axis (offset not absolute).
int selectY;		//< Selected slug grid tile on Y-axis (offset not absolute).
int prevX;			//< Previous selected slug grid tile on X-axis (offset not absolute).
int prevY;			//< Previous selected slug grid tile on Y-axis (offset not absolute).

int hangarEmptyT = 2;

HANGAR_TILE_SIZE h_size;
int h_width;
int h_height;
int startGridX = 3;	//< Starting tile X of slug grid
int startGridY = 3;	//< Starting tile Y of slug grid

//---------------------------------------------------------------------------------
// Program entry point
//---------------------------------------------------------------------------------
int main(void)
//---------------------------------------------------------------------------------
{

	h_size = HANGAR_MEDIUM;
	h_width = 5;
	h_height = 5;

	// Enable Large background, use Screenblock 31 and enable 16-color mode
	REG_BG0CNT = TEXTBG_SIZE_512x512 | SCREEN_BASE(SB_PAGE) | BG_256_COLOR;
	SetMode(MODE_0 | BG0_ON);		// screen mode & background to display

	// Load tile set and palette 
	DecodePCX(GROUND_EXP_pcx, CHAR_BASE_ADR(0), BG_PALETTE);

	tiles = Tile_InitTileMatrix(h_height, h_width);
	slug = Slug_CreateSlug(tiles, h_width, h_height, SLUG_SIZE);

	hangar_Init();

	drawSlug(slug);

	// Set up the interrupt handlers
	irqInit();
	// Enable Vblank Interrupt to allow VblankIntrWait
	irqEnable(IRQ_VBLANK);

	// Load all necessary image data
	//graphics_LoadImage(title_pcx, &PaletteBuffer);
	//graphics_LoadImage(title_pulse_pcx, &PulsePaletteBuffer);

	//splash_screen_eff = splash_PulseGray;	// Set the initial screen mode
	//splash_set_pal1(&PaletteBuffer);		// Load the first palette
	//splash_set_pal2(&PulsePaletteBuffer);	// Load the second palette

	//dprintf("Initialised application with palettes %p, %p\n", &PaletteBuffer, &PulsePaletteBuffer);

	while (1)
	{
		VBlankIntrWait();
		//graphics_Update();
		// Process key inputs
		input_key_reads();
		hangar_HandleInputs();

		if (input_key_pressed(KEY_SELECT)) {
			Slug_DestroySlug(slug);
			slug = Slug_CreateSlug(tiles, h_width, h_height, SLUG_SIZE);

			hangar_Init();
			drawSlug(slug);
		}

		//splash_HandleInputs();
	}

	free(tiles);
	Slug_DestroySlug(slug);

}

void drawSlug(Slug * s) {
	for (int i = 0; i < s->size; i++) {
		drawHangarTile(s->coords[i]->x * h_size + startGridX, s->coords[i]->y * h_size + startGridY, 8, 8);
	}
}

void hangar_InitSelector() {
	selectX = 0;
	selectY = 0;
	prevX = 0;
	prevY = 0;
	// Draw initial starting tile
	drawHangarTile(startGridX, startGridY, 1, 0);
}

void hangar_Init() {

	clearScreenblock(SB_PAGE, 13);

	// Draw the slug ground map
	drawGroundMap(SB_PAGE, h_size, startGridX, startGridY, h_width, h_height);

	// Draw initial starting tile
	drawHangarTile(startGridX, startGridY, 1, 0);
}

void clearScreenblock(int sb, int filltile) {
	for (int x = 0; x < 32; x++) {
		for (int y = 0; y < 32; y++) {
			MAP[SB_PAGE][y][x] = filltile;
		}
	}
}

void hangar_HandleInputs() {

	// Input handling for selected tile x-coordinate movement.
	if (input_key_pressed(KEY_LEFT) && selectX > 0) {
		prevX = selectX;
		selectX -= h_size;
	}
	else if (input_key_pressed(KEY_RIGHT) && selectX < hangar_total_width - h_size) {
		prevX = selectX;
		selectX += h_size;
	}

	// Input handling for selected tile y-coordinate movement
	if (input_key_pressed(KEY_UP) && selectY > 0) {
		prevY = selectY;
		selectY -= h_size;
	}
	else if (input_key_pressed(KEY_DOWN) && selectY < hangar_total_height - h_size) {
		prevY = selectY;
		selectY += h_size;
	}

	// Check if the user wishes to increase or decrease the hangar tile size and do so.
	if (input_key_pressed(KEY_L) && h_size > HANGAR_SMALL) {
		h_size--;
		hangar_Init();
		hangar_InitSelector();
	}

	if (input_key_pressed(KEY_R) && h_size < HANGAR_LARGE) {
		h_size++;
		hangar_Init();
		hangar_InitSelector();
	}

	// If the selected tile has changed, mark it as selected and clear the previous tile.
	if (prevX != selectX | prevY != selectY) {

		// Clear the previous tile
		drawHangarTile(startGridX + selectX, startGridY + selectY, 1, 0);

		// Draw the new tile
		drawHangarTile(startGridX + prevX, startGridY + prevY, 2, 0);

		prevX = selectX;
		prevY = selectY;
	}

}


void splash_HandleInputs() {
	if (input_key_pressed(KEY_UP) && splash_screen_eff != splash_PulseGray)				splash_screen_eff = splash_PulseGray;
	else if (input_key_pressed(KEY_RIGHT) && splash_screen_eff != splash_Pulse_Title)	splash_screen_eff = splash_Pulse_Title;
	else if (input_key_pressed(KEY_DOWN) && splash_screen_eff != splash_FadeOut)		splash_screen_eff = splash_FadeOut;
	else if (input_key_pressed(KEY_LEFT))												graphics_TransNewImage(main_menu_pcx);
}