#ifndef _RANDLIB_H
#define _RANDLIB_H

/**
 * A direct copy of Tonclib's random number generator.
 * @see http://www.coranac.com/tonc/text/gfx.htm#cd-qran
 */

int __qran_seed = 42;     //< Seed to be used.

/**
 * Seed setter for replacing __qran_seed with a new seed.
 * @param seed The new seed to use.
 * @returns The old seed.
 */
int sqran(int seed)
{
	int old = __qran_seed;
	__qran_seed = seed;
	return old;
}

/**
 * Pseudo-random number generator
 * based on a Linear Congruential Generator.
 * @return The new random number generated by the routine.
 */
static inline int qran()
{
	__qran_seed = 1664525 * __qran_seed + 1013904223;
	return (__qran_seed >> 16) & 0x7FFF;
}

/**
 * A wrapper of the qran number generator which ranges the number to the specified range.
 * @param min The minimum number of the range.
 * @param max The maximum number of the range (up to 8000h or 32768).
 * @return The randomly generated value.
 */
static inline int qran_range(int min, int max)
{
	return (qran()*(max - min) >> 15) + min;
}

#endif
