//---------------------------------------------------------------------------------
// GBA PCXView sample code for devkitARM - http://www.devkit.tk
// Suitable for a splash screen for a game
//---------------------------------------------------------------------------------
#include "gba_video.h"
#include "gba_systemcalls.h"
#include "gba_input.h"
#include "gba_interrupt.h"
#include "mappy.h"
#include "pcx.h"
#include "fade.h"

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "title_pcx.h"
#include "title_pulse_pcx.h"
#include "main_menu_pcx.h"

#include "splash_scr.h"
#include "graphics_controller.h"
#include "input_controller.h"

//---------------------------------------------------------------------------------
// storage space for palette data
//---------------------------------------------------------------------------------
u16 EWRAM_DATA PaletteBuffer[256];
u16 EWRAM_DATA PulsePaletteBuffer[256];

// System variables


// Method declarations

void handleControls();

//---------------------------------------------------------------------------------
// Program entry point
//---------------------------------------------------------------------------------
int main(void)
//---------------------------------------------------------------------------------
{
	// Set up the interrupt handlers
	irqInit();
	// Enable Vblank Interrupt to allow VblankIntrWait
	irqEnable(IRQ_VBLANK);

	SetMode(MODE_4 | BG2_ON);		// screen mode & background to display

	// Load all necessary image data
	graphics_LoadImage(title_pcx, PaletteBuffer);
	graphics_LoadImage(title_pulse_pcx, PulsePaletteBuffer);

	splash_screen_eff = splash_pulse_gray;	// Set the initial screen mode
	splash_set_pal1(&PaletteBuffer);		// Load the first palette
	splash_set_pal2(&PulsePaletteBuffer);	// Load the second palette

	dprintf("Initialised application with palettes %p, %p\n", &PaletteBuffer, &PulsePaletteBuffer);

	while (1)
	{
		VBlankIntrWait();
		splash_update();
		if (state == 1) graphics_TransNewImage(main_menu_pcx, &PaletteBuffer);	// If in transition mode, update transition
		// Process key inputs
		input_key_reads();
		handleControls();
	}
}

void handleControls() {
	if (input_key_pressed(KEY_UP) && splash_screen_eff != splash_pulse_gray)			splash_screen_eff = splash_pulse_gray;
	else if (input_key_pressed(KEY_RIGHT) && splash_screen_eff != splash_pulse_title)	splash_screen_eff = splash_pulse_title;
	else if (input_key_pressed(KEY_DOWN) && splash_screen_eff != splash_fade_out)		splash_screen_eff = splash_fade_out;
	else if (input_key_pressed(KEY_LEFT)) {
		graphics_TransNewImage(main_menu_pcx, &PaletteBuffer);
	}
}