//---------------------------------------------------------------------------------
// GBA PCXView sample code for devkitARM - http://www.devkit.tk
// Suitable for a splash screen for a game
//---------------------------------------------------------------------------------
#include "gba_video.h"
#include "gba_systemcalls.h"
#include "gba_input.h"
#include "gba_interrupt.h"
#include "pcx.h"
#include "fade.h"

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "title_pcx.h"

//---------------------------------------------------------------------------------
// storage space for palette data
//---------------------------------------------------------------------------------
u16 PaletteBuffer[256];

unsigned int frame;

u32 pressed;
u32 released;
u32 held;

void (*screen_eff)();
void fade_out();
void pulse_gray();
void key_reads();
void handleControls();
void VblankInterrupt();

//---------------------------------------------------------------------------------
// Program entry point
//---------------------------------------------------------------------------------
int main(void)
//---------------------------------------------------------------------------------
{
	// Set up the interrupt handlers
	irqInit();

	irqSet(IRQ_VBLANK, VblankInterrupt);

	// Enable Vblank Interrupt to allow VblankIntrWait
	irqEnable(IRQ_VBLANK);

	// Allow Interrupts
	REG_IME = 0;

	SetMode(MODE_4 | BG2_ON);		// screen mode & background to display

	DecodePCX(title_pcx, (u16*)VRAM, PaletteBuffer);

	screen_eff = pulse_gray;

	FadeToPalette(PaletteBuffer, 60);

	while (1)
	{
		VBlankIntrWait();
	}
}

// Create a screen 'fade out' effect by first fading the palette to gray, then black
void fade_out() {
	if ((frame & 60) == 0) {
		FadeToBlack(60);
	}

}

void pulse_gray() {
	if ((frame & 60) == 0) {
		FadeToPalette(PaletteBuffer, 60);
	} if ((frame & 120) == 0) {
		FadeToGrayScale(4, 60);
	}
}

//---------------------------------------------------------------------------------
void VblankInterrupt()
//---------------------------------------------------------------------------------
{
	frame += 1;

	key_reads();
	handleControls();

	(*screen_eff)();
	//if ((frame & 60) == 0) {
	//	FadeToPalette(PaletteBuffer, 60);
	//} if ((frame & 120) == 0) {
	//	FadeToGrayScale(4, 60);
	//}
}

void key_reads() {
	if ((frame & 7) == 0) {
		// Check for key updates and record the results to a buffer for later use
		scanKeys();
		pressed = keysDown();
		held = keysHeld();
		released = keysUp();
	}
}

void handleControls() {
	if (pressed & KEY_START) {
		if (screen_eff != pulse_gray) screen_eff = pulse_gray;
	}
	else if (pressed & KEY_SELECT) {
		if (screen_eff != fade_out) screen_eff = fade_out;
	}
}
